<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="AWS-PVDI-45" failures="0" tests="1" name="Runner.TestApplication" time="192.463" errors="1" timestamp="2024-02-16T15:53:24 IST" skipped="0">
  <testcase classname="Runner.TestApplication" name="runScenario" time="192.463">
    <error message="Expected condition failed: waiting for visibility of element located by By.xpath: //*[@psfcname=&quot;toAccount_lookupKey&quot;] (tried for 100 second(s) with 1000 milliseconds interval)
Build info: version: &#039;4.11.0&#039;, revision: &#039;040bc5406b&#039;
System info: os.name: &#039;Windows 10&#039;, os.arch: &#039;amd64&#039;, os.version: &#039;10.0&#039;, java.version: &#039;17.0.8.1&#039;
Driver info: driver.version: unknown" type="org.openqa.selenium.TimeoutException">
      <![CDATA[org.openqa.selenium.TimeoutException: Expected condition failed: waiting for visibility of element located by By.xpath: //*[@psfcname="toAccount_lookupKey"] (tried for 100 second(s) with 1000 milliseconds interval)
Build info: version: '4.11.0', revision: '040bc5406b'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.8.1'
Driver info: driver.version: unknown
at org.openqa.selenium.support.ui.FluentWait.timeoutException(FluentWait.java:262)
at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:230)
at utilities.UserUtility_614.waitHelper(UserUtility_614.java:53)
at utilities.UserUtility_614.elementIsVisible(UserUtility_614.java:635)
at stepdefinitions.Transfers.user_626_validate_the_to_account_field_is_available_in_scheduled_own_account_transfer(Transfers.java:106)
at âœ½.User_626 Validate the To Account field is Available in Scheduled own account transfer(file:///C:/Users/inindc00626/git/DigitalBanking/Azentio_DigitalBanking_Kailash/src/test/java/features/ScheduledTransfers.feature:19)
]]>
    </error>
  </testcase> <!-- runScenario -->
</testsuite> <!-- Runner.TestApplication -->
